/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    contexts: Context;
    terms: Term;
    translations: Translation;
    sources: Source;
    examples: Example;
    reviews: Review;
    'import-batches': ImportBatch;
    'generation-jobs': GenerationJob;
    'ai-drafts': AiDraft;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    contexts: ContextsSelect<false> | ContextsSelect<true>;
    terms: TermsSelect<false> | TermsSelect<true>;
    translations: TranslationsSelect<false> | TranslationsSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    examples: ExamplesSelect<false> | ExamplesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'import-batches': ImportBatchesSelect<false> | ImportBatchesSelect<true>;
    'generation-jobs': GenerationJobsSelect<false> | GenerationJobsSelect<true>;
    'ai-drafts': AiDraftsSelect<false> | AiDraftsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'reader' | 'contributor' | 'reviewer' | 'language_expert' | 'moderator' | 'admin';
  bio?: string | null;
  areasOfExpertise?: (number | Category)[] | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  nameEn: string;
  nameMn: string;
  slug: string;
  descriptionEn?: string | null;
  descriptionMn?: string | null;
  parentCategory?: (number | null) | Category;
  displayOrder: number;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contexts".
 */
export interface Context {
  id: number;
  nameEn: string;
  nameMn: string;
  slug: string;
  descriptionEn?: string | null;
  descriptionMn?: string | null;
  category: number | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms".
 */
export interface Term {
  id: number;
  headwordEn: string;
  normalizedHeadwordEn: string;
  slug: string;
  partOfSpeech?: ('noun' | 'verb' | 'adjective' | 'adverb' | 'phrase' | 'acronym' | 'other') | null;
  pronunciation?: string | null;
  shortDefinitionEn: string;
  explanationEn: string;
  explanationMn: string;
  usageNoteEn?: string | null;
  usageNoteMn?: string | null;
  workflowStatus: 'draft' | 'needs_review' | 'needs_discussion' | 'reviewed' | 'approved' | 'archived';
  reviewStatus: 'not_reviewed' | 'ai_draft' | 'community_reviewed' | 'human_reviewed' | 'expert_reviewed';
  categories: (number | Category)[];
  contexts?: (number | Context)[] | null;
  recommendedTranslation?: (number | null) | Translation;
  relatedTerms?: (number | Term)[] | null;
  createdBy?: (number | null) | User;
  reviewedBy?: (number | null) | User;
  approvedBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations".
 */
export interface Translation {
  id: number;
  term: number | Term;
  translationMn: string;
  translationType:
    | 'recommended'
    | 'alternative'
    | 'context_specific'
    | 'formal'
    | 'informal'
    | 'literal'
    | 'rejected'
    | 'deprecated';
  context?: (number | null) | Context;
  register: 'general' | 'formal' | 'informal' | 'technical' | 'academic' | 'legal' | 'medical' | 'business';
  explanationEn?: string | null;
  explanationMn?: string | null;
  usageNote?: string | null;
  status: 'draft' | 'needs_review' | 'approved' | 'rejected' | 'deprecated';
  reviewStatus: 'not_reviewed' | 'ai_draft' | 'community_reviewed' | 'human_reviewed' | 'expert_reviewed';
  voteScore?: number | null;
  createdBy?: (number | null) | User;
  reviewedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  term: number | Term;
  translation?: (number | null) | Translation;
  title: string;
  publisher: string;
  author?: string | null;
  url: string;
  publicationDate?: string | null;
  accessedDate?: string | null;
  sourceType:
    | 'government'
    | 'standards_body'
    | 'official_documentation'
    | 'academic'
    | 'dictionary'
    | 'textbook'
    | 'professional_usage'
    | 'news'
    | 'community_discussion'
    | 'other';
  licenseNote?: string | null;
  excerptNote?: string | null;
  isVerified?: boolean | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "examples".
 */
export interface Example {
  id: number;
  term: number | Term;
  translation?: (number | null) | Translation;
  exampleEn: string;
  exampleMn: string;
  context?: (number | null) | Context;
  source?: (number | null) | Source;
  status: 'draft' | 'needs_review' | 'approved' | 'rejected';
  reviewStatus: 'not_reviewed' | 'ai_draft' | 'community_reviewed' | 'human_reviewed' | 'expert_reviewed';
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  term: number | Term;
  translation?: (number | null) | Translation;
  reviewer: number | User;
  reviewType: 'linguistic' | 'technical' | 'editorial' | 'source_validation' | 'final_approval';
  decision: 'approved' | 'changes_requested' | 'rejected';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-batches".
 */
export interface ImportBatch {
  id: number;
  name: string;
  sourceTitle: string;
  sourceUrl?: string | null;
  category?: (number | null) | Category;
  status: 'pending' | 'validating' | 'processing' | 'completed' | 'completed_with_errors' | 'failed';
  promptVersion?: string | null;
  modelName?: string | null;
  schemaVersion?: string | null;
  totalRows?: number | null;
  acceptedRows?: number | null;
  rejectedRows?: number | null;
  duplicateRows?: number | null;
  validationReport?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generation-jobs".
 */
export interface GenerationJob {
  id: number;
  idempotencyKey: string;
  inputHeadword: string;
  category: number | Category;
  context?: (number | null) | Context;
  importBatch?: (number | null) | ImportBatch;
  status: 'queued' | 'running' | 'retry_scheduled' | 'completed' | 'failed' | 'cancelled';
  stage: 'research' | 'generation' | 'critique' | 'validation' | 'routing' | 'complete';
  attemptCount: number;
  maxAttempts: number;
  modelProvider: string;
  modelName: string;
  researchPromptVersion: string;
  generationPromptVersion: string;
  critiquePromptVersion: string;
  schemaVersion: string;
  inputPayload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sourceInputSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  researchRawOutput?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  generationRawOutput?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  critiqueRawOutput?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  validationErrors?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorCode?: string | null;
  errorMessage?: string | null;
  queuedAt: string;
  startedAt?: string | null;
  completedAt?: string | null;
  nextRetryAt?: string | null;
  inputTokens?: number | null;
  outputTokens?: number | null;
  estimatedCostUsd?: number | null;
  latencyMs?: number | null;
  requestedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-drafts".
 */
export interface AiDraft {
  id: number;
  term?: (number | null) | Term;
  generationJob: number | GenerationJob;
  inputHeadword: string;
  inputCategory: number | Category;
  inputContext?: (number | null) | Context;
  sources?: (number | Source)[] | null;
  researchPayload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  generatedPayload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  critiquePayload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  schemaVersion: string;
  modelProvider: string;
  modelName: string;
  promptVersion: string;
  confidenceDimensions: {
    conceptUnderstanding: 'low' | 'medium' | 'high';
    translationNaturalness: 'low' | 'medium' | 'high';
    domainAccuracy: 'low' | 'medium' | 'high';
    sourceSupport: 'low' | 'medium' | 'high';
    ambiguity: 'low' | 'medium' | 'high';
  };
  riskLevel: 'low' | 'medium' | 'high';
  reviewRoute:
    | 'fast_review'
    | 'language_review'
    | 'domain_review'
    | 'community_discussion'
    | 'duplicate_review'
    | 'blocked';
  status: 'generated' | 'editing' | 'needs_review' | 'accepted' | 'partially_accepted' | 'rejected';
  generatedBy: string;
  reviewedBy?: (number | null) | User;
  reviewOutcome?: ('accepted' | 'modified' | 'rejected') | null;
  acceptedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  modifiedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rejectionReasons?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'contexts';
        value: number | Context;
      } | null)
    | ({
        relationTo: 'terms';
        value: number | Term;
      } | null)
    | ({
        relationTo: 'translations';
        value: number | Translation;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'examples';
        value: number | Example;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'import-batches';
        value: number | ImportBatch;
      } | null)
    | ({
        relationTo: 'generation-jobs';
        value: number | GenerationJob;
      } | null)
    | ({
        relationTo: 'ai-drafts';
        value: number | AiDraft;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  areasOfExpertise?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  nameEn?: T;
  nameMn?: T;
  slug?: T;
  descriptionEn?: T;
  descriptionMn?: T;
  parentCategory?: T;
  displayOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contexts_select".
 */
export interface ContextsSelect<T extends boolean = true> {
  nameEn?: T;
  nameMn?: T;
  slug?: T;
  descriptionEn?: T;
  descriptionMn?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms_select".
 */
export interface TermsSelect<T extends boolean = true> {
  headwordEn?: T;
  normalizedHeadwordEn?: T;
  slug?: T;
  partOfSpeech?: T;
  pronunciation?: T;
  shortDefinitionEn?: T;
  explanationEn?: T;
  explanationMn?: T;
  usageNoteEn?: T;
  usageNoteMn?: T;
  workflowStatus?: T;
  reviewStatus?: T;
  categories?: T;
  contexts?: T;
  recommendedTranslation?: T;
  relatedTerms?: T;
  createdBy?: T;
  reviewedBy?: T;
  approvedBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations_select".
 */
export interface TranslationsSelect<T extends boolean = true> {
  term?: T;
  translationMn?: T;
  translationType?: T;
  context?: T;
  register?: T;
  explanationEn?: T;
  explanationMn?: T;
  usageNote?: T;
  status?: T;
  reviewStatus?: T;
  voteScore?: T;
  createdBy?: T;
  reviewedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  term?: T;
  translation?: T;
  title?: T;
  publisher?: T;
  author?: T;
  url?: T;
  publicationDate?: T;
  accessedDate?: T;
  sourceType?: T;
  licenseNote?: T;
  excerptNote?: T;
  isVerified?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "examples_select".
 */
export interface ExamplesSelect<T extends boolean = true> {
  term?: T;
  translation?: T;
  exampleEn?: T;
  exampleMn?: T;
  context?: T;
  source?: T;
  status?: T;
  reviewStatus?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  term?: T;
  translation?: T;
  reviewer?: T;
  reviewType?: T;
  decision?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-batches_select".
 */
export interface ImportBatchesSelect<T extends boolean = true> {
  name?: T;
  sourceTitle?: T;
  sourceUrl?: T;
  category?: T;
  status?: T;
  promptVersion?: T;
  modelName?: T;
  schemaVersion?: T;
  totalRows?: T;
  acceptedRows?: T;
  rejectedRows?: T;
  duplicateRows?: T;
  validationReport?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generation-jobs_select".
 */
export interface GenerationJobsSelect<T extends boolean = true> {
  idempotencyKey?: T;
  inputHeadword?: T;
  category?: T;
  context?: T;
  importBatch?: T;
  status?: T;
  stage?: T;
  attemptCount?: T;
  maxAttempts?: T;
  modelProvider?: T;
  modelName?: T;
  researchPromptVersion?: T;
  generationPromptVersion?: T;
  critiquePromptVersion?: T;
  schemaVersion?: T;
  inputPayload?: T;
  sourceInputSnapshot?: T;
  researchRawOutput?: T;
  generationRawOutput?: T;
  critiqueRawOutput?: T;
  validationErrors?: T;
  errorCode?: T;
  errorMessage?: T;
  queuedAt?: T;
  startedAt?: T;
  completedAt?: T;
  nextRetryAt?: T;
  inputTokens?: T;
  outputTokens?: T;
  estimatedCostUsd?: T;
  latencyMs?: T;
  requestedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-drafts_select".
 */
export interface AiDraftsSelect<T extends boolean = true> {
  term?: T;
  generationJob?: T;
  inputHeadword?: T;
  inputCategory?: T;
  inputContext?: T;
  sources?: T;
  researchPayload?: T;
  generatedPayload?: T;
  critiquePayload?: T;
  schemaVersion?: T;
  modelProvider?: T;
  modelName?: T;
  promptVersion?: T;
  confidenceDimensions?:
    | T
    | {
        conceptUnderstanding?: T;
        translationNaturalness?: T;
        domainAccuracy?: T;
        sourceSupport?: T;
        ambiguity?: T;
      };
  riskLevel?: T;
  reviewRoute?: T;
  status?: T;
  generatedBy?: T;
  reviewedBy?: T;
  reviewOutcome?: T;
  acceptedFields?: T;
  modifiedFields?: T;
  rejectionReasons?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}